site_name: Smarthome
site_url: https://dieknops.de/smarthome/
theme: 
  name: material
  logo: 'img/site/logo.png'
  favicon: 'img/site/favicon.ico'
  palette:
    scheme: slate
  #not working - prev_next_buttons_location: none
extra_css: [css/index.css]
markdown_extensions:
- admonition
#Icons https://petershaggynoble.github.io/MDI-Sandbox/
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tilde
- pymdownx.details
- toc:
    permalink: True
nav: 
- Home: 'index.md'
- Architektur: 'architektur/index.md'
- Raspberry:
  - Installation: 'install/raspi.md'
  - VPN: 'install/vpn.md'
- FHEM: 
  - Installation: 'install/fhem.md'
  - Solar: 'fhemtipps/fhem_solar.md'
  - Gaszähler: 'fhemtipps/fhem_zaehler.md'
  - Tipps: 'fhemtipps/fhem_tipps.md'
- ESP: 
  - Installation: 'install/esp.md'
  - Sensoren: 'esptipps/sensoren.md'
  - Tipps: 'esptipps/esp_tipps.md'
- Elektronik: 'elektronik/elek_tipps.md'
- KNX: 'install/knx.md'
- Grandstream: 'grandstream/grandstream_install.md'
- FritzBox: 'fritz/fritz.md'
- Farblegende: 'install/legende.md'