site_name: Smarthome
theme: 
  name: material
  logo: 'img/site/logo.png'
  favicon: 'img/site/favicon.ico'
  #not working - prev_next_buttons_location: none
extra_css: [css/index.css]
markdown_extensions:
- admonition
#Icons https://petershaggynoble.github.io/MDI-Sandbox/
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.tilde
- pymdownx.details
- toc:
    permalink: True
nav: 
- Home: 'index.md'
- Architektur: 'architektur/index.md'
- Raspberry: 'install/raspi.md'
- FHEM: 
  - Installation: 'install/fhem.md'
  - Tipps: 'fhemtipps/fhem_tipps.md'
- ESP: 
  - Installation: 'install/esp.md'
  - Tipps: 'esptipps/esp_tipps.md'
- KNX: 'install/knx.md'
- Farblegende: 'install/legende.md'